### ISSUE TITLE
ImportError: DLL load failed while importing onnxruntime_pybind11_state: 找不到指定的程序。

### ISSUE THREAD

**Issue by cloudslee** [RQLuo/MixTeX-Latex-OCR#13]
Traceback (most recent call last):
  File "donjc\MixTeX-v1.0.py", line 2, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "mixtex\__init__.py", line 7, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "onnxruntime\__init__.py", line 57, in <module>
  File "onnxruntime\__init__.py", line 23, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "onnxruntime\capi\_pybind_state.py", line 32, in <module>
ImportError: DLL load failed while importing onnxruntime_pybind11_state: 找不到指定的程序。

**Comment by RQLuo** [comment]
试试下载微软补丁：

x86: https://aka.ms/vs/16/release/VC_redist.x86.exe
x64: https://aka.ms/vs/16/release/VC_redist.x64.exe

**Comment by cloudslee** [comment]
我的环境是win7，貌似mixtex不支持。
另外，看了一下源码中哪里不支持win7呢？

**Comment by RQLuo** [comment]
很多地方都不支持win7，对我的打包程序不太好适配。py打包的一次开发处处不能用。我不太懂这些开发，我是非专业的。😂 全平台我也就只能用网页版实现了。

**Comment by cloudslee** [comment]
这个源码本身是支持win7的吧，我自己来打包的话，应该怎么弄?

**Comment by RQLuo** [comment]
我没有win7，你可以试试在本地能不能运行colab
